package com.rafaborrego.audit.contract;

import com.rafaborrego.audit.controller.auditControllerImpl;
import com.rafaborrego.audit.mapper.BeanMapper;
import com.rafaborrego.audit.service.auditService;
import io.restassured.module.mockmvc.RestAssuredMockMvc;
import ma.glasnost.orika.MapperFactory;
import ma.glasnost.orika.impl.DefaultMapperFactory;
import org.junit.Before;

import static org.mockito.Mockito.mock;

/**
 * Base class for the contract tests on the Producer side.
 * The tests are generated by Spring Cloud in the target folder: generated-test-sources/contracts
 */
public class BaseContractTest {

    @Before
    public void setup() {

        BeanMapper beanMapper = configureBeanMapper();
        auditService auditServiceMock = configureauditServiceMock();

        RestAssuredMockMvc.standaloneSetup(
                new auditControllerImpl(auditServiceMock, beanMapper));
    }

    private auditService configureauditServiceMock() {

        auditService auditService = mock(auditService.class);

        return auditService;
    }

    private BeanMapper configureBeanMapper() {

        MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();

        return new BeanMapper(mapperFactory);
    }
}
